services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/jodone/data/mariadb'
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/jodone/data/wordpress'

networks:
  inception:
    driver: bridge