services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

volumes:
  mariadb_data:

networks:
  inception: